apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: client
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30932
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: client
  sessionAffinity: None
  type: LoadBalancer