apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
    fluxcd.io/sync-gc-mark: sha256.Y-TFljT3eF3eekoiB1yLjHD-p0ZgzVhzpkolOpeAqQg
  name: front
  namespace: b6005795
spec:
  externalTrafficPolicy: Cluster
  ports:
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front
  sessionAffinity: None
  type: LoadBalancer
